workflows:
  ios-basic:
    name: iOS Basic Build
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.mathosproject
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install --repo-update

      - name: Build iOS
        script: |
          flutter build ios --no-codesign --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/build/Logs/Build/*.xcactivitylog
    publishing:
      email:
        recipients:
          - user@example.com # Remplacez par votre email