workflows:
  ios-basic:
    name: iOS Basic Build
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.mathosproject
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Pod clean and install
        script: |
          cd ios
          rm -rf Pods/
          rm -rf Podfile.lock
          pod cache clean --all
          pod repo update
          pod install

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/build/Logs/Build/*.xcactivitylog