workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.mathosproject
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          cd ios
          pod install
          xcodebuild build -workspace Runner.xcworkspace -scheme Runner -configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log