workflows:
  ios-firebase:
    name: iOS Firebase Distribution
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.mathosproject
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FIREBASE_APP_ID: "1:906508848480:ios:3eed7bc23c7801e7562205"
    scripts:
      - name: Set up project and clean
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.podspec
          flutter pub cache repair
          flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod repo update
          pod cache clean --all
          pod install --repo-update

      - name: Flutter build
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --no-codesign

      - name: Upload to Firebase
        script: |
          curl -sL https://firebase.tools | bash
          firebase appdistribution:distribute "build/ios/ipa/mathosproject.ipa" \
            --app "$FIREBASE_APP_ID" \
            --groups "testers" \
            --release-notes "Nouvelle version test de Mathos"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log