workflows:
  ios-firebase:
    name: iOS Firebase Distribution
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.mathosproject
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FIREBASE_APP_ID: "1:906508848480:ios:3eed7bc23c7801e7562205"
    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Pod clean and install
        script: |
          cd ios
          rm -rf Pods/
          rm -rf Podfile.lock
          pod cache clean --all
          pod repo update
          pod install --repo-update

      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive COMPILER_INDEX_STORE_ENABLE=NO
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist /Users/builder/export_options.plist -exportPath build/ios/ipa

      - name: Upload to Firebase
        script: |
          curl -sL https://firebase.tools | bash
          firebase appdistribution:distribute "build/ios/ipa/mathosproject.ipa" \
            --app "$FIREBASE_APP_ID" \
            --groups "testers" \
            --release-notes "Nouvelle version test de Mathos"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log