// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvYAl4IvgG_nZChW6SzzLhlFwnDks2NeE',
    appId: '1:906508848480:web:daa72f5917ed9091562205',
    messagingSenderId: '906508848480',
    projectId: 'mathosproject-f2a53',
    authDomain: 'mathosproject-f2a53.firebaseapp.com',
    storageBucket: 'mathosproject-f2a53.appspot.com',
    measurementId: 'G-HSDE9PL9D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtqwvZEv5K_wq7xf7iGdHAdd-iJxs7omY',
    appId: '1:906508848480:android:4d2d6fde8c0ac329562205',
    messagingSenderId: '906508848480',
    projectId: 'mathosproject-f2a53',
    storageBucket: 'mathosproject-f2a53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjw43X9r9swQMMJl2et_wNPvD4hLtSUOI',
    appId: '1:906508848480:ios:3eed7bc23c7801e7562205',
    messagingSenderId: '906508848480',
    projectId: 'mathosproject-f2a53',
    storageBucket: 'mathosproject-f2a53.appspot.com',
    androidClientId: '906508848480-4k22a4ci1n4ji2fqqki0kh8vsr1kcibc.apps.googleusercontent.com',
    iosClientId: '906508848480-7bj02o473bch0kiv08at0f2mbjlijf82.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathosproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjw43X9r9swQMMJl2et_wNPvD4hLtSUOI',
    appId: '1:906508848480:ios:3eed7bc23c7801e7562205',
    messagingSenderId: '906508848480',
    projectId: 'mathosproject-f2a53',
    storageBucket: 'mathosproject-f2a53.appspot.com',
    androidClientId: '906508848480-4k22a4ci1n4ji2fqqki0kh8vsr1kcibc.apps.googleusercontent.com',
    iosClientId: '906508848480-7bj02o473bch0kiv08at0f2mbjlijf82.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathosproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvYAl4IvgG_nZChW6SzzLhlFwnDks2NeE',
    appId: '1:906508848480:web:a753d9e1794c6241562205',
    messagingSenderId: '906508848480',
    projectId: 'mathosproject-f2a53',
    authDomain: 'mathosproject-f2a53.firebaseapp.com',
    storageBucket: 'mathosproject-f2a53.appspot.com',
    measurementId: 'G-C6BV7BP12S',
  );
}
