platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Dépendances Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  # Intégration Flutter
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end
