platform :ios, '13.0'

require File.expand_path('../.symlinks/plugins/plugin_helper.rb', __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Dépendances Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  # Lignes nécessaires pour Flutter
  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end
